---
creation_rules:
  - path_regex: .*secret\.sops\.ya?ml$
    key_groups:
      - age:
          - age1zeqkpfz7e3s207ynea0z0auc0mrct0pc7w4sh6j3d0c4qac3dahqj9ufdg
          - age1tdwlq9y4jgejkhasqwynw5uaen9xwatcvr52l70trsdxkeyvlesqjnh7l8
          - age16p3zls5n0jks6amszwcuaqgl5dyuyf8k8wgeyrw562s5s88xtq3qq046fh
          - age1j3fexl0zmam73qqmf23m3u830kfp84v9dxrtyre02mparz9dssts6qux2w
