---
creation_rules:
  - path_regex: .*secret\.sops\.ya?ml$
    key_groups:
      - age:
          - age1zeqkpfz7e3s207ynea0z0auc0mrct0pc7w4sh6j3d0c4qac3dahqj9ufdg
          - age1tdwlq9y4jgejkhasqwynw5uaen9xwatcvr52l70trsdxkeyvlesqjnh7l8
