# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  chezmoi-vim = {
    pname = "chezmoi-vim";
    version = "9b9f0479856f5ce61daa1d5889ff379b18a109a5";
    src = fetchFromGitHub ({
      owner = "alker0";
      repo = "chezmoi.vim";
      rev = "9b9f0479856f5ce61daa1d5889ff379b18a109a5";
      fetchSubmodules = false;
      sha256 = "sha256-Cti0Clg/rPbO+tEWfdY+q3cCAwnB3l7MFRteSmrfigQ=";
    });
    date = "2023-02-10";
  };
  k8s-snippets = {
    pname = "k8s-snippets";
    version = "8cd98bc8ae103b9fdb2c95556eab27bfad42f7d2";
    src = fetchFromGitHub ({
      owner = "budimanjojo";
      repo = "k8s-snippets";
      rev = "8cd98bc8ae103b9fdb2c95556eab27bfad42f7d2";
      fetchSubmodules = false;
      sha256 = "sha256-AQZewr1ZBjPlM8VZcjre5o3SB+mEJOt9xq3uERIz3u0=";
    });
    date = "2023-02-24";
  };
  luasnip = {
    pname = "luasnip";
    version = "v1.2.1";
    src = fetchFromGitHub ({
      owner = "L3MON4D3";
      repo = "LuaSnip";
      rev = "v1.2.1";
      fetchSubmodules = false;
      sha256 = "sha256-6NJPOu5f5ycu9l53CZB7prVNj61UaVz706tOrk5c860=";
    });
  };
  mason-lspconfig-nvim = {
    pname = "mason-lspconfig-nvim";
    version = "93e58e100f37ef4fb0f897deeed20599dae9d128";
    src = fetchFromGitHub ({
      owner = "williamboman";
      repo = "mason-lspconfig.nvim";
      rev = "93e58e100f37ef4fb0f897deeed20599dae9d128";
      fetchSubmodules = false;
      sha256 = "sha256-LBBrANy949YMHvW9sRoPZtVB6poFERGIqaJHNx6q3rQ=";
    });
    date = "2023-02-14";
  };
  mason-tool-installer-nvim = {
    pname = "mason-tool-installer-nvim";
    version = "6ca38efeb0406dea8da6c97f61d6f6ef30ab0576";
    src = fetchFromGitHub ({
      owner = "WhoIsSethDaniel";
      repo = "mason-tool-installer.nvim";
      rev = "6ca38efeb0406dea8da6c97f61d6f6ef30ab0576";
      fetchSubmodules = false;
      sha256 = "sha256-4PErcgZHuHPq3BHkXYFqpwRJlj/XZYdt8wqPUis8kCg=";
    });
    date = "2023-01-26";
  };
  oil-nvim = {
    pname = "oil-nvim";
    version = "0b2a4ddde1c8a881c2d1620a673c12914bd6d1dc";
    src = fetchFromGitHub ({
      owner = "stevearc";
      repo = "oil.nvim";
      rev = "0b2a4ddde1c8a881c2d1620a673c12914bd6d1dc";
      fetchSubmodules = false;
      sha256 = "sha256-WEDzEDV9vDGkPjbl1q6GDtgE0vhk0qQWKi79MRTT8uc=";
    });
    date = "2023-02-24";
  };
  sad-nvim = {
    pname = "sad-nvim";
    version = "4cd87acbe4d9106ff2a42c4cd850dc5313bdc696";
    src = fetchFromGitHub ({
      owner = "ray-x";
      repo = "sad.nvim";
      rev = "4cd87acbe4d9106ff2a42c4cd850dc5313bdc696";
      fetchSubmodules = false;
      sha256 = "sha256-HijZK6xRx8pTvWlmtXHC50GAH8AHbsAn0yThYRT6cOQ=";
    });
    date = "2023-02-21";
  };
  tokyonight-gtk-theme = {
    pname = "tokyonight-gtk-theme";
    version = "6e4ee110d8cbcd88b28b451595bf3a5a0ee194e1";
    src = fetchFromGitHub ({
      owner = "Fausto-Korpsvart";
      repo = "Tokyo-Night-GTK-Theme";
      rev = "6e4ee110d8cbcd88b28b451595bf3a5a0ee194e1";
      fetchSubmodules = false;
      sha256 = "sha256-DjDrcirM7ksb3Yu07wwUZInUr87mGI6nN420kgR+AOE=";
    });
    date = "2023-02-20";
  };
  tokyonight-icon-theme = {
    pname = "tokyonight-icon-theme";
    version = "6e4ee110d8cbcd88b28b451595bf3a5a0ee194e1";
    src = fetchFromGitHub ({
      owner = "Fausto-Korpsvart";
      repo = "Tokyo-Night-GTK-Theme";
      rev = "6e4ee110d8cbcd88b28b451595bf3a5a0ee194e1";
      fetchSubmodules = false;
      sha256 = "sha256-DjDrcirM7ksb3Yu07wwUZInUr87mGI6nN420kgR+AOE=";
    });
    date = "2023-02-20";
  };
}
