require('grug-far').setup {
  keymaps = {
    replace = { n = '<localleader>W' },
    syncLocations = { n = '<localleader>w' },
    syncLine = { n = '<localleader><space>' },
    applyNext = { n = '<localleader>j' },
    applyPrev = { n = '<localleader>k' },
    openLocation = { n = '<enter>' },
    previewLocation = { n = '<localleader>i' },
    refresh = { n = '<localleader>f' },
    close = { n = 'q' },
    help = { n = 'g?' },
    abort = { n = '<localleader>qq' },
    qflist = false,
    historyOpen = false,
    historyAdd = false,
    openNextLocation = false,
    openPrevLocation = false,
    gotoLocation = false,
    pickHistoryEntry = false,
    toggleShowCommand = false,
    swapEngine = false,
    swapReplacementInterpreter = false,
    syncNext = false,
    syncPrev = false,
    syncFile = false,
    nextInput = false,
    prevInput = false,
  },
}
