# This file was generated by nvfetcher, please do not modify it manually.
{ fetchgit, fetchurl, fetchFromGitHub, dockerTools }:
{
  abbreviation-tips = {
    pname = "abbreviation-tips";
    version = "v0.7.0";
    src = fetchFromGitHub {
      owner = "gazorby";
      repo = "fish-abbreviation-tips";
      rev = "v0.7.0";
      fetchSubmodules = false;
      sha256 = "sha256-F1t81VliD+v6WEWqj1c1ehFBXzqLyumx5vV46s/FZRU=";
    };
  };
  chezmoi-vim = {
    pname = "chezmoi-vim";
    version = "abf37336437867cbd99ce2f8849b717415391cc3";
    src = fetchFromGitHub {
      owner = "alker0";
      repo = "chezmoi.vim";
      rev = "abf37336437867cbd99ce2f8849b717415391cc3";
      fetchSubmodules = false;
      sha256 = "sha256-S1/myC1dEydi1F9a6XV0lJW3S/wWQe+A2ZXPo8GbtQo=";
    };
    date = "2024-07-26";
  };
  guihua-lua = {
    pname = "guihua-lua";
    version = "0cc9631914ffcbe3e474e809c610d12a75b660cf";
    src = fetchFromGitHub {
      owner = "ray-x";
      repo = "guihua.lua";
      rev = "0cc9631914ffcbe3e474e809c610d12a75b660cf";
      fetchSubmodules = false;
      sha256 = "sha256-34BvyXHCk82g3lS1WPIxitIdP/f99JPcmXDgRdvb8cw=";
    };
    date = "2025-04-20";
  };
  k8s-snippets = {
    pname = "k8s-snippets";
    version = "ba5ca9b1b12a3b1c3fb0237494380f4feff668c8";
    src = fetchFromGitHub {
      owner = "budimanjojo";
      repo = "k8s-snippets";
      rev = "ba5ca9b1b12a3b1c3fb0237494380f4feff668c8";
      fetchSubmodules = false;
      sha256 = "sha256-vVDKI9HR1QqJDHh10oZQ9Zr01gvJhj1iIEgwP+gssx8=";
    };
    date = "2023-12-13";
  };
  luasnip = {
    pname = "luasnip";
    version = "v2.3.0";
    src = fetchFromGitHub {
      owner = "L3MON4D3";
      repo = "LuaSnip";
      rev = "v2.3.0";
      fetchSubmodules = false;
      sha256 = "sha256-E1Ov6aF9DJ0poVM6q6jK1ypsJf6cRzHqC2Gi6u9kai0=";
    };
  };
  mason-lspconfig-nvim = {
    pname = "mason-lspconfig-nvim";
    version = "1a31f824b9cd5bc6f342fc29e9a53b60d74af245";
    src = fetchFromGitHub {
      owner = "williamboman";
      repo = "mason-lspconfig.nvim";
      rev = "1a31f824b9cd5bc6f342fc29e9a53b60d74af245";
      fetchSubmodules = false;
      sha256 = "sha256-+Rji3UH32QQZADqQhMcJpgmkwbDumKaBlZO6cqNvUGY=";
    };
    date = "2025-02-15";
  };
  mason-tool-installer-nvim = {
    pname = "mason-tool-installer-nvim";
    version = "1255518cb067e038a4755f5cb3e980f79b6ab89c";
    src = fetchFromGitHub {
      owner = "WhoIsSethDaniel";
      repo = "mason-tool-installer.nvim";
      rev = "1255518cb067e038a4755f5cb3e980f79b6ab89c";
      fetchSubmodules = false;
      sha256 = "sha256-eQ+HglVqZMD0wOw9EhNZcVdP/tNvdfhLgVNxOHCp448=";
    };
    date = "2025-04-06";
  };
  oil-nvim = {
    pname = "oil-nvim";
    version = "302bbaceeafc690e6419e0c8296e804d60cb9446";
    src = fetchFromGitHub {
      owner = "stevearc";
      repo = "oil.nvim";
      rev = "302bbaceeafc690e6419e0c8296e804d60cb9446";
      fetchSubmodules = false;
      sha256 = "sha256-r1yGuS40xVJERyWFh+tWWEqKbm2jCweT81Bd5ysIu5Q=";
    };
    date = "2025-03-30";
  };
  sad-nvim = {
    pname = "sad-nvim";
    version = "d5bb4e98b42ae0084ae6ec03aa285d1b2fa1ba8e";
    src = fetchFromGitHub {
      owner = "ray-x";
      repo = "sad.nvim";
      rev = "d5bb4e98b42ae0084ae6ec03aa285d1b2fa1ba8e";
      fetchSubmodules = false;
      sha256 = "sha256-ldU9B6ABUy9GM/K+ysRtplj3sdFf0jjqv3L74oTMiF0=";
    };
    date = "2024-10-28";
  };
  tmux-fish = {
    pname = "tmux-fish";
    version = "db0030b7f4f78af4053dc5c032c7512406961ea5";
    src = fetchFromGitHub {
      owner = "budimanjojo";
      repo = "tmux.fish";
      rev = "db0030b7f4f78af4053dc5c032c7512406961ea5";
      fetchSubmodules = false;
      sha256 = "sha256-rRibn+FN8VNTSC1HmV05DXEa6+3uOHNx03tprkcjjs8=";
    };
    date = "2025-04-07";
  };
  tokyonight-gtk-theme = {
    pname = "tokyonight-gtk-theme";
    version = "e9b4dd50f0c7d091d6c1e6797ba703182b92b5e2";
    src = fetchFromGitHub {
      owner = "Fausto-Korpsvart";
      repo = "Tokyo-Night-GTK-Theme";
      rev = "e9b4dd50f0c7d091d6c1e6797ba703182b92b5e2";
      fetchSubmodules = false;
      sha256 = "sha256-FTlIkvMU0fMPwwGm2FB+9YDh1E8i5UM8N4kBApJcM4g=";
    };
    date = "2025-04-16";
  };
  tokyonight-icon-theme = {
    pname = "tokyonight-icon-theme";
    version = "e9b4dd50f0c7d091d6c1e6797ba703182b92b5e2";
    src = fetchFromGitHub {
      owner = "Fausto-Korpsvart";
      repo = "Tokyo-Night-GTK-Theme";
      rev = "e9b4dd50f0c7d091d6c1e6797ba703182b92b5e2";
      fetchSubmodules = false;
      sha256 = "sha256-FTlIkvMU0fMPwwGm2FB+9YDh1E8i5UM8N4kBApJcM4g=";
    };
    date = "2025-04-16";
  };
}
