[tokyonight-icon-theme]
src.git = "https://github.com/Fausto-Korpsvart/Tokyo-Night-GTK-Theme"
fetch.github = "Fausto-Korpsvart/Tokyo-Night-GTK-Theme"
[chezmoi-vim]
src.git = "https://github.com/alker0/chezmoi.vim"
fetch.github = "alker0/chezmoi.vim"
[k8s-snippets]
src.git = "https://github.com/budimanjojo/k8s-snippets"
fetch.github = "budimanjojo/k8s-snippets"
[abbreviation-tips]
src.github_tag = "gazorby/fish-abbreviation-tips"
fetch.github = "gazorby/fish-abbreviation-tips"
[tmux-fish]
src.git = "https://github.com/budimanjojo/tmux.fish"
fetch.github = "budimanjojo/tmux.fish"
[fish-completion-sync]
src.git = "https://github.com/iynaix/fish-completion-sync"
fetch.github = "iynaix/fish-completion-sync"
